on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '1 1 1 * *'

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt
      - name: format
        run: cargo fmt -- --check

  test-notls:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: [nightly]
        features: [""]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: Run clippy
        run: cargo clippy --features=${{ matrix.features }} --all-targets
      - name: Build
        run: cargo build --features=${{ matrix.features }} --verbose
      - name: Run tests
        run: cargo test --features=${{ matrix.features }} --verbose

  test-tls:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: [nightly]
        features: ["tls"]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: Run clippy
        run: cargo clippy --features=${{ matrix.features }} --all-targets
      - name: Build
        run: cargo build --features=${{ matrix.features }} --verbose
      - name: Run tests
        run: cargo test --features=${{ matrix.features }} --verbose
