on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '1 1 1 * *'

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - name: format
        run: cargo fmt -- --check

  test-notls:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        toolchain: [stable, beta, nightly]
        features: [""]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: Run clippy
        run: cargo clippy ${{ matrix.feature_bug }} --features=${{ matrix.feature_subcommands }} --all-targets
      - name: Build
        run: cargo build ${{ matrix.feature_bug }} --features=${{ matrix.feature_subcommands }} --verbose
      - name: Run tests
        run: cargo test ${{ matrix.feature_bug }} --features=${{ matrix.feature_subcommands }} --verbose

  test-tls:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        toolchain: [nightly]
        features: ["tls"]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: Run clippy
        run: cargo clippy ${{ matrix.feature_bug }} --features=${{ matrix.feature_subcommands }} --all-targets
      - name: Build
        run: cargo build ${{ matrix.feature_bug }} --features=${{ matrix.feature_subcommands }} --verbose
      - name: Run tests
        run: cargo test ${{ matrix.feature_bug }} --features=${{ matrix.feature_subcommands }} --verbose
